# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
      
  - package-ecosystem: "pip"
    # Location of the package configs in the repository
    directory: "/"
    schedule:
      # Check for updates daily
      interval: "weekly"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
